### ISSUE TITLE
CustomObject does not extends Resource<T>

### ISSUE THREAD

**Issue by JudeNiroshan** [commercetools/commercetools-jvm-sdk#1976] opened 2019-09-17 15:18 UTC
I have encountered a problem where I can not use a generic workflow for any resource in CTP platform. I found out that it is because CustomObject does not extends Resource<T> like any other resource.

https://github.com/commercetools/commercetools-jvm-sdk/blob/456a6e97c776b36d8619474deb7ed7a07353db4f/commercetools-models/src/main/java/io/sphere/sdk/products/Product.java#L42

Is this a mistake or does this needs to be fixed?
https://github.com/commercetools/commercetools-jvm-sdk/blob/456a6e97c776b36d8619474deb7ed7a07353db4f/commercetools-models/src/main/java/io/sphere/sdk/customobjects/CustomObject.java#L175

**Comment by alex-ct** [comment] 2019-09-18 08:32
@JudeNiroshan can't be changed. it is meant to be this way.

**Comment by heshamMassoud** [comment] 2019-09-23 15:40
Sorry, I don't understand why this "meant to be used this way"? Could you please elaborate @alex-ct

In my opinion, It makes a lot of sense, at least design-wise, to be used this way. Actually if it doesn't extend the `Resource` interface it breaks the design of the SDK.

A `CustomObject` is a `Resource` with a `id`, `version`, `createdAt`, `lastModifiedAt`, etc.. just as a Product, Category, etc.. on our platform. 

In the sync library we have designed some of our generic base classes based on the `Resource` interface which has some fields (`id`, `version`, `createdAt`, `lastModifiedAt`) that are common on any platform resource. This saves us from a lot of redundant code. Now, that the `CustomObject` does not `extend` this `Resource` interface, forces us to duplicate logic just for CustomObjects.

**Comment by alex-ct** [comment] 2019-09-24 09:28
@heshamMassoud 
The problem is that CustomObject extends only some interfaces that Resource extends. It looks like this is done for a reason. Otherwise it would just extend Resource. Things like this happened a lot in the past, where it looked like we could change something but then it broke stuff. There is also a lot of code being generated based on these interfaces with is really hard to check. I will change it to extend Resource and try to run all tests and also check again with other team members to make sure we dont break anything. If it all works out, we will change it to extend Resource.

**Comment by heshamMassoud** [comment] 2019-09-24 09:51
@alex-ct thank you for willing to invest the time to look into it.

**Comment by heshamMassoud** [comment] 2019-10-11 08:46
ok, understood. It definitely makes sense since they are already distinguished like that on the API level, with the same endpoint for update and create for custom objects (and separate create update for the rest endpoints). 

My bad, I didn't see the `ResourceView` interface which has all the `getId()`, `getVersion()`, `getCreatedAt()`, `getLastModifiedAt()` in its contract. And actually `CustomObject` extends `ResourceView`. So all good :)

Sorry for disturbing and thanks again for taking the time to investigate this.

**Comment by heshamMassoud** [comment] 2019-10-11 08:47
I guess we can close the issue 😊, @JudeNiroshan?

**Comment by JudeNiroshan** [comment] 2019-10-11 09:12
yes, we can close the issue :)

**Closed** 2019-10-11 09:12 UTC
