### ISSUE TITLE
Null key in Reference

### ISSUE THREAD

**Issue by selo-ecube** [commercetools/commercetools-jvm-sdk#1519] opened 2017-09-04 15:49 UTC
Please invest more work into your API design and implementation.

In 1.21.0 you changed the return type of `ProductDraft.getCategories()` from `Set<Reference<Category>>` to `Set<ResourceIdentifier<Category>>`. `ResourceIdentifier` provides a `getKey()` method besides `getId()`. It's nice that there is a shift towards keys as a uniform way to identify resources.

It's not funny thought, that `ProductDraft.getCategories()` returns instances of `ReferenceImpl` that inherits `Reference.getKey()` in which you took the "freedom" to declare:

```
    /**
     * In references the key should always be null
     * @return null
     */
    @Nullable
    @Override
    default String getKey() {
        return null;
    }
```

When an object can be referred to by its key, it makes a lot of sense to make that key accessible via the reference, e.g. for testing. Please fix that as soon as possible. Thanks!

(We create `ProductctDraft`s by passing `Category` instances to them, `ProductDraft` uses  `Category.toReference()` internally, which does not retain the category key even if it exists.)

**Comment by katmatt** [comment] 2017-09-05 08:35
Thanks for reporting this bug and we plan to fix it as soon as possible. The implementation  of `Reference#getKey()` returning `null` is correct, because a reference will never have a key. But I agree that the concept of a `ResourceIdentifier` and `Reference' can be confusing. 
The bug you reported was caused by an invalid conversion of a `Category` to a `Reference<Category>` (which dropped the key) and then to a `ResourceIdentifier<Category>`. Removing the intermediate `Reference<Category>` will solve this problem.

**Comment by katmatt** [comment] 2017-09-08 08:14
@selo-ecube After thinking more about it, I'm unsure if we really can provide a fix for this problem. 

Let me explain my thoughts: 
A `ResourceIdentifier` can either have an `id` or have a `key`. Using a `key` is especially useful if you import data and haven't yet stored the corresponding resource on our platform. But in your example you are already working with persisted categories, which already have an `id`. And how should our SDK decide which kind of resource identifier (with an id or a key) you  would like to use? It just uses the safest fallback and that's using the`ìd`, because the `key` is optional.

If you really want to make sure that the `ProductDraft` contains category resource identifiers with keys, you have to be explicit about it:
```
        Function<Category, ResourceIdentifier> toResourceIdentifierWithKey = c ->
                ResourceIdentifier.ofKey(c.getKey(), Category.resourceTypeId());
        List<Category> categories = ...
        Set<ResourceIdentifier<Category>> withKeys = categories.stream()
                .map(toResourceIdentifierWithKey)
                .collect(Collectors.toSet());
        
        ProductDraftBuilder productDraftBuilder = ...
        
        productDraftBuilder.categories(withKeys)
```
What do you think?

**Comment by selo-ecube** [comment] 2017-09-11 09:45
> A ResourceIdentifier can either have an id or have a key.

While ResourceIdentifier.ofIdOrKey(...) has a name that can be understood like ID XOR key, the implementation passes both ID and key to ResourceIdentifierImpl, i.e. a ResourceIdentifier can have both an ID and a key.

> And how should our SDK decide which kind of resource identifier (with an id or a key) you would like to use? It just uses the safest fallback and that's using theìd, because the key is optional.

Why not add both ID and key to the resource identifier, if both are available from the Category? If the key is not available, you would only add the ID, of course.

**Comment by katmatt** [comment] 2017-09-12 08:05
Our JVM SDK follows the specification of our API (see http://dev.commercetools.com/http-api-types.html#resourceidentifier), which implies a  XOR relation between the id and the optional key. That means that our backend will always use the id if it's available. And because of the XOR, our backend won't validate the key if it's send with an id. That means that a user of our JVM SDK could send any invalid key as long as the id is valid and our backend will never raise an error.

In my opinion this could hide potential bugs on your side:
Let's assume that you're writing an import and always use resource identifiers with an id and a key. But since our platform ignores the key, you never realize that you're sending invalid keys. Then you decide to run your import on an empty project and it suddenly stops working because you never correctly imported the keys that you used in your resource identifier.

**Comment by selo-ecube** [comment] 2017-09-12 10:00
I wasn't aware of the part of the HTTP API on resource identifiers. Thanks for the hint! However, the HTTP API specification does not mention any relation between key-based and id-based resource identifiers and treats them as different types. The XOR relation is created by the JVM-SDK using a single type for resource identifiers with ids and with keys. Is there a need for ResourceIdentifier.ofIdOrKey(...) then? Otherwise it might be better to remove this method so users cannot create such misleading resource-identifiers that contain both ID and key.

While it would be possible that you create key-based resource identifiers for categories when categories have a key and id-based one otherwise, there might be other API users who always want id-based resource identifiers, thought. I'll use the solution you proposed in your second comment. I'm sorry for the long argument!

I think the underlying problem is the visibility of the internal UUIDs in the Commercetools API and keys being optional. We ourselves never use the internal UUIDs to refer to Commercetools resources because the UUIDs are not stable and do not fit our CI style of development. Of course the API needs these UUIDs because external keys are not required. Maybe in the long term keys become mandatory and UUIDs can be hidden so there is only one way of creating resource identifiers. For objects not having keys, the JVM-SDK might then provide easy means of using UUIDs as keys.

Thanks for your help!

**Comment by katmatt** [comment] 2017-09-12 11:40
You're welcome and I like to have a good discussion 😉 And I like the idea to not expose our internal ids via our api. An extension of your suggestion would be to initialize a missing key with the id, thus making the key in resource mandatory while keeping it optional in a resource draft. But it just an idea and we don't plan to move into that direction in the near future 😉

**Closed** 2017-09-18 10:48 UTC
