### ISSUE TITLE
Async HTTP client and Spring Boot 2 version clash

### ISSUE THREAD

**Issue by garfailed** [commercetools/commercetools-jvm-sdk#1751] opened 2018-04-21 14:45 UTC
Hi,

When we upgraded to Spring Boot 2, we ran into this error:
```
WARN  io.netty.util.concurre.DefaultPromise - An exception was thrown by org.asynchttpclient.netty.request.NettyRequestSender$1.operationComplete()
java.lang.NoSuchMethodError: io.netty.channel.DefaultChannelId.newInstance()Lio/netty/channel/DefaultChannelId;
```

As it turns out both [Spring Boot](https://github.com/spring-projects/spring-boot/blob/v2.0.1.RELEASE/spring-boot-project/spring-boot-dependencies/pom.xml#L132), and the [async-http-client](https://github.com/AsyncHttpClient/async-http-client/blob/2afae6007c76e32d6de3db41e0c297725aa1ff90/pom.xml#L379) (at least the [version present](https://github.com/commercetools/commercetools-jvm-sdk/blob/80070c46bac5c7ecbe252098690b4b5dd6316074/pom.xml#L85) in the Commercetools SDK) use the `netty.version` property.

This causes the Spring Boot property to override the async-http-client's Netty version, and since the version in Commercetools is a bit out of date it fails with the error linked above.

The workaround was to explicitly specify the older `netty.version` in our own `pom.xml`, and since nothing else uses Netty, this doesn't cause any issues (for us at least).

**Comment by acbeni** [comment] 2018-04-23 08:58
The problem is related to some breaking change in netty2, 
In order to be able to work with Spring Boot 2 , just make sure you remove the following dependencies:

```xml
<dependency>
    <groupId>com.commercetools.sdk.jvm.core</groupId>
    <artifactId>commercetools-java-client-ahc-2_0</artifactId> . 
    <version>${used.version}</version>
</dependency>
<dependency>
    <groupId>com.commercetools.sdk.jvm.core</groupId>
    <artifactId>sdk-http-ahc-2_0</artifactId>
    <version>${used.version}</version>
</dependency>
```
and replace it with

```xml
<dependency>
    <groupId>com.commercetools.sdk.jvm.core</groupId>
    <artifactId>sdk-http-apache-async</artifactId>
    <version>${used.version}</version>
</dependency>
<dependency>
    <groupId>com.commercetools.sdk.jvm.core</groupId>
    <artifactId>commercetools-java-client-apache-async</artifactId>
    <version>${used.version}</version>
</dependency>
```


and that's it, this client has no dependency on netty so there will be no conflict.

**Comment by acbeni** [comment] 2018-04-23 08:59
if that works for you let me know so i close the issue @garfailed

**Comment by garfailed** [comment] 2018-04-23 09:39
Thank you, that was the solution we originally used, and what was suggested by your support, but it was bugging me that I didn't know why the `async-http-client` failed. I just opened this issue to let people know that there is a workaround if they prefer the `async-http-client` library.

Do you have any plans to upgrade to the `async-http-client` to a more recent version (`2.4.5` currently)?

**Comment by acbeni** [comment] 2018-04-23 09:43
Updating `async-http-client` should't  be a big deal, i will add it to the next release.

**Closed** 2018-04-26 09:07 UTC
Labels: review
